// Decorative JSON Schemas for runtime form-level validation in the frontend.
// **The backend is always the source of truth.** A successful client-side
// validation does NOT imply the server will accept the input; conversely,
// the server may apply stricter rules these schemas don't model
// (cross-field constraints, port conflicts, encoder availability).
//
// Schemas are auto-generated by `scripts/regenerate-validation.sh` from
// `spiritstream-server`'s `/api/v1/openapi.json`. Do not edit them by hand.

import openapi from './openapi.json' with { type: 'json' };

export { openapi };

// Re-export the per-component schemas. Add a new line here when a new
// `#[derive(ToSchema)]` Rust struct or response body gets added to the
// utoipa annotations and regeneration produces a new `schemas/<Name>.json`.
import HealthResponse from './schemas/HealthResponse.json' with { type: 'json' };
import ReadyResponse from './schemas/ReadyResponse.json' with { type: 'json' };
import ReadyCheckFailure from './schemas/ReadyCheckFailure.json' with { type: 'json' };
import ProfilesListResponse from './schemas/ProfilesListResponse.json' with { type: 'json' };
import ProfileShowQuery from './schemas/ProfileShowQuery.json' with { type: 'json' };
import ProfileSaveRequest from './schemas/ProfileSaveRequest.json' with { type: 'json' };
import ProfileSaveResponse from './schemas/ProfileSaveResponse.json' with { type: 'json' };
import ProfileDeleteResponse from './schemas/ProfileDeleteResponse.json' with { type: 'json' };
import ProfileIsEncryptedResponse from './schemas/ProfileIsEncryptedResponse.json' with { type: 'json' };
import ApiErrorBody from './schemas/ApiErrorBody.json' with { type: 'json' };

export const schemas = {
  HealthResponse,
  ReadyResponse,
  ReadyCheckFailure,
  ProfilesListResponse,
  ProfileShowQuery,
  ProfileSaveRequest,
  ProfileSaveResponse,
  ProfileDeleteResponse,
  ProfileIsEncryptedResponse,
  ApiErrorBody,
} as const;

export type SchemaName = keyof typeof schemas;
