//! Aggregated OpenAPI document for the `/api/v1/*` surface and its
//! HTTP serving handler.
//!
//! K7 split: pulled out of `v1/mod.rs` so the orchestrator stays under
//! the 600 LOC ceiling as the schema registry grows. Adding a new typed
//! handler still follows the cadence documented at the top of
//! `v1/mod.rs`:
//!
//!   1. Annotate the handler with `#[utoipa::path(...)]`.
//!   2. Register the function in `ApiDoc::paths(...)` below.
//!   3. Register any request/response structs in `components(schemas(...))`.
//!   4. Mount the route in `public_router()` or `protected_router()`
//!      back in `mod.rs`.
//!
//! Re-exported from `v1::*` so callers see the same symbol name.

use axum::{response::IntoResponse, Json};
use utoipa::OpenApi;

use super::*;

/// Aggregated OpenAPI document for the `/api/v1/*` surface.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "SpiritStream HTTP API",
        version = "1.0.0",
        description = "Versioned REST surface for SpiritStream. All clients (web, Tauri desktop, Tauri mobile, CLI, automation) speak this API. See the rewrite plan for the migration shape."
    ),
    servers((url = "/api/v1", description = "API v1")),
    paths(
        v1_health,
        v1_ready,
        v1_profiles_list,
        v1_profile_show,
        v1_profile_save,
        v1_profile_delete,
        v1_profile_is_encrypted,
        v1_settings_get,
        v1_settings_save,
        v1_settings_profiles_path,
        v1_settings_export,
        v1_settings_clear_data,
        v1_safety_panic,
        v1_audit_log,
        v1_streams_validate,
        v1_streams_status,
        v1_streams_start,
        v1_streams_start_all,
        v1_streams_stop,
        v1_streams_stop_all,
        v1_streams_retry,
        v1_streams_toggle_target,
        v1_profile_activate,
        v1_profile_unlock,
        v1_profile_decrypt,
        v1_profile_lock,
        v1_profile_locked_list,
        v1_system_encoder_presets,
        v1_system_app_version,
        v1_system_audit_app_update_failure,
        v1_system_client_config,
        v1_system_encoders_proxy,
        v1_system_ffmpeg_test_proxy,
        v1_system_ffmpeg_path_proxy,
        v1_system_ffmpeg_update_proxy,
        v1_system_ffmpeg_validate_proxy,
        v1_system_rtmp_test_proxy,
        v1_system_logs_proxy,
        v1_system_logs_export_proxy,
        v1_security_rotate_machine_key_proxy,
        v1_profile_summaries_proxy,
        v1_profile_validate_input_proxy,
        v1_profile_order_get_proxy,
        v1_profile_order_set_proxy,
        v1_profile_order_ensure_proxy,
        v1_themes_list_proxy,
        v1_themes_install_proxy,
        v1_themes_refresh_proxy,
        v1_theme_tokens_proxy,
        v1_obs_state_proxy,
        v1_obs_get_config_proxy,
        v1_obs_set_config_proxy,
        v1_obs_is_connected_proxy,
        v1_obs_connect_proxy,
        v1_obs_disconnect_proxy,
        v1_obs_start_stream_proxy,
        v1_obs_stop_stream_proxy,
        v1_discord_test_webhook_proxy,
        v1_discord_send_notification_proxy,
        v1_discord_reset_cooldown_proxy,
        v1_chat_status_proxy,
        v1_chat_recent_messages_proxy,
        v1_chat_connect_proxy,
        v1_chat_disconnect_all_proxy,
        v1_chat_platform_status_proxy,
        v1_chat_disconnect_proxy,
        v1_chat_retry_proxy,
        v1_chat_reidentify_proxy,
        v1_chat_send_proxy,
        v1_chat_is_connected_proxy,
        v1_chat_log_status_proxy,
        v1_chat_export_log_proxy,
        v1_chat_search_session_proxy,
        v1_oauth_get_config_proxy,
        v1_oauth_set_config_proxy,
        v1_oauth_set_provider_credentials_proxy,
        v1_oauth_is_configured_proxy,
        v1_oauth_start_flow_proxy,
        v1_oauth_complete_flow_proxy,
        v1_oauth_get_account_proxy,
        v1_oauth_disconnect_proxy,
        v1_oauth_forget_proxy,
        v1_oauth_refresh_token_proxy,
        v1_stream_target_disabled_proxy,
    ),
    components(schemas(
        HealthResponse,
        ReadyResponse,
        ReadyCheckFailure,
        ProfilesListResponse,
        ProfileShowQuery,
        ProfileSaveRequest,
        ProfileSaveResponse,
        ProfileDeleteResponse,
        ProfileIsEncryptedResponse,
        SettingsWire,
        SettingsSaveRequest,
        SettingsSaveResponse,
        SettingsProfilesPathResponse,
        SettingsExportRequest,
        SettingsExportResponse,
        SettingsClearDataResponse,
        SafetyPanicResponse,
        AuditLogResponse,
        AuditChainStatusWire,
        ChatPlatformWire,
        ChatConnectionStatusWire,
        ChatPlatformStatusWire,
        ChatSendResultWire,
        ChatLogStatusWire,
        ChatAckResponse,
        ChatConnectedResponse,
        ChatSendRequest,
        ChatReidentifyRequest,
        ChatReidentifyResponse,
        ChatSearchRequest,
        ChatExportRequest,
        // G5 chat-config-wire (request body for POST /chat/connections).
        ChatConfigWire,
        ChatCredentialsWire,
        TwitchAuthWire,
        YouTubeAuthWire,
        SubsystemStatus,
        StreamValidateRequest,
        StreamValidateResponse,
        StreamStatusResponse,
        StreamStartRequest,
        StreamStartResponse,
        StreamStartAllRequest,
        StreamStartAllResponse,
        StreamStopAllResponse,
        StreamRetryResponse,
        StreamToggleTargetRequest,
        StreamToggleTargetResponse,
        ProfileActivateRequest,
        ProfileUnlockRequest,
        ProfileUnlockResponse,
        ProfileDecryptRequest,
        ProfileDecryptResponse,
        ProfileLockResponse,
        ProfileLockedListResponse,
        EncoderPresetsResponse,
        ClientConfigResponse,
        RangeU32,
        AppVersionResponse,
        AppUpdateFailureRequest,
        AuditRecordedResponse,
        SystemAckResponse,
        LogsResponse,
        LogsQuery,
        LogsExportRequest,
        FFmpegVersionResponse,
        FFmpegPathResponse,
        FFmpegValidatePathResponse,
        FFmpegValidatePathRequest,
        FFmpegUpdateQuery,
        FFmpegVersionInfoWire,
        EncoderKindWire,
        EncoderMetaWire,
        EncodersWire,
        RtmpTestRequest,
        RtmpTestResultWire,
        RotationReportWire,
        OAuthProviderSummaryWire,
        OAuthProviderSetupWire,
        OAuthStepWire,
        OAuthConsoleFieldWire,
        OAuthProviderCredentialsRequest,
        OAuthConfiguredResponse,
        OAuthAckResponse,
        OAuthForgetResponse,
        OAuthConfigRequest,
        OAuthFlowResponse,
        OAuthUserInfoResponse,
        OAuthTokensResponse,
        OAuthAccountStatusResponse,
        OAuthCompleteRequest,
        OAuthRefreshRequest,
        ObsConnectionStatusWire,
        ObsStreamStatusWire,
        IntegrationDirectionWire,
        ObsStateResponse,
        ObsConfigResponse,
        ObsSetConfigRequest,
        ObsConnectedResponse,
        ObsAckResponse,
        ProfileSummaryWire,
        ProfileAckResponse,
        ProfileOrderMapResponse,
        ProfileValidateInputRequest,
        ProfileOrderSetRequest,
        // G5 profile-wire tree (used by GET /profiles/{name} + activate).
        ProfileWire,
        RtmpInputWire,
        OutputGroupWire,
        VideoSettingsWire,
        AudioSettingsWire,
        ContainerSettingsWire,
        StreamTargetWire,
        ProfileSettingsWire,
        BackendSettingsWire,
        ObsSettingsWire,
        ObsIntegrationDirectionWire,
        DiscordSettingsWire,
        ChatSettingsWire,
        OAuthAccountWire,
        OAuthSettingsWire,
        // G5 chat-message-wire tree (used by POST /chat/log/search).
        ChatMessageWire,
        ChatMessageDirectionWire,
        ChatAuthorWire,
        ReplyContextWire,
        ElevatedTierWire,
        FragmentColorWire,
        EmoteProviderWire,
        BadgeProviderWire,
        TextStyleWire,
        MessageFragmentWire,
        ChatEventWire,
        SuperChatPayloadWire,
        SuperStickerPayloadWire,
        HypeChatPayloadWire,
        NewSponsorPayloadWire,
        MilestonePayloadWire,
        GiftedPayloadWire,
        CheerPayloadWire,
        RaidPayloadWire,
        BanPayloadWire,
        PollPayloadWire,
        RoomStatePayloadWire,
        ThemeModeWire,
        ThemeSummaryWire,
        ThemeTokensResponse,
        ThemeInstallRequest,
        WebhookResultResponse,
        DiscordAckResponse,
        DiscordWebhookTestRequest,
        StreamTargetDisabledResponse,
        ApiErrorBody,
        RotateMachineKeyRequest,
    ))
)]
pub struct ApiDoc;

/// Serve the OpenAPI document describing the `/api/v1/*` surface.
///
/// The current emitter (utoipa 4 with axum 0.7) produces an OpenAPI 3.0.3
/// document. The rewrite plan calls for 3.1, which requires bumping to
/// utoipa 5 + axum 0.8 — that upgrade is folded into a later cleanup pass
/// since the type-generator we use (`@hey-api/openapi-ts`)
/// accepts both 3.0 and 3.1 specs without behavior change.
pub async fn serve_openapi() -> impl IntoResponse {
    Json(ApiDoc::openapi())
}
