/// Composed Zustand store for profile state.
///
/// Slices live in sibling files (`core.ts`, `password.ts`, `output-groups.ts`)
/// and are merged here. Each slice's `get()` returns the full combined state
/// so cross-slice calls (e.g. password.submitPassword → core.loadProfile,
/// output-groups.addOutputGroup → core.saveProfile) keep working.
///
/// Event subscriptions (`profile_activated`, `oauth_token_expired`) live here
/// because they touch the combined store at module level.

import { create } from 'zustand';
import { events } from '@spiritstream/api-client';
import { logger } from '@/lib/logger';
import { toast } from '@/hooks/useToast';
import type { ProfileActivatedEvent } from '@spiritstream/types';
import { createCoreSlice } from './core';
import { createPasswordSlice } from './password';
import { createOutputGroupsSlice } from './output-groups';
import { applyProfileSettings } from './applySettings';
import type { ProfileState } from './types';

export type { ProfileState } from './types';

export const useProfileStore = create<ProfileState>()((...args) => ({
  ...createCoreSlice(...args),
  ...createPasswordSlice(...args),
  ...createOutputGroupsSlice(...args),
}));

/**
 * Backend → frontend bridge: the server emits a single `profile_activated`
 * event with the consolidated settings (theme, language, OBS, etc.) whenever
 * `ProfileService::activate()` runs. The payload type is generated by ts-rs
 * from `crates/core/src/services/profile_manager.rs` so the wire shape stays
 * in sync with Rust without a hand-rolled mirror.
 *
 * Subscribed from `AppContent` (after the server-readiness gate passes) —
 * NOT at module-import time. Subscribing at module-import opened the
 * WebSocket before the server was listening, producing the
 * "WebSocket connection failed" cascade in the boot console.
 */
export async function subscribeProfileActivated(): Promise<() => void> {
  return events.on<ProfileActivatedEvent>('profile_activated', (payload) => {
    const settings = useProfileStore.getState().current?.settings;
    if (!settings) return;
    applyProfileSettings({
      ...settings,
      themeId: payload.themeId,
      language: payload.language,
      showNotifications: payload.showNotifications,
    });
  });
}

/**
 * Backend → frontend bridge: the server emits `oauth_token_expired` whenever
 * a proactive refresh inside `refresh_expiring_oauth_tokens` fails — typically
 * because the refresh token itself was revoked or expired. The frontend just
 * renders; the recovery action (re-running the OAuth flow) happens when the
 * user clicks reconnect.
 *
 * Subscribed from `AppContent` (after the server-readiness gate passes) —
 * same rationale as `subscribeProfileActivated`.
 */
interface OAuthTokenExpiredPayload {
  provider: string;
}

export async function subscribeOAuthTokenExpired(): Promise<() => void> {
  return events.on<OAuthTokenExpiredPayload>('oauth_token_expired', (payload) => {
    logger.warn(`[ProfileStore] OAuth token expired for ${payload.provider}; re-auth required.`);
    const label = payload.provider.charAt(0).toUpperCase() + payload.provider.slice(1);
    toast.info(`${label} sign-in expired — reconnect to send chat or stream.`);
  });
}
